jdbc:
  url: jdbc:mysql://localhost:3306/idde_vbim2101_jpa?allowPublicKeyRetrieval=true&useSSL=false
  username: root
  password: root
  poolsize: 10
  jdbcDriver: com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true